# Generated by Django 5.2.7 on 2025-10-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "stock_code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("stock_name", models.CharField(max_length=100)),
                ("market_type", models.CharField(default="KOSPI", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
