# Generated by Django 5.2.7 on 2025-10-20 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stocks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[("BUY", "매수"), ("SELL", "매도")],
                        max_length=4,
                        verbose_name="주문 유형",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="주문 수량")),
                (
                    "price_type",
                    models.CharField(
                        choices=[("MARKET", "시장가"), ("LIMIT", "지정가")],
                        default="MARKET",
                        max_length=6,
                        verbose_name="가격 유형",
                    ),
                ),
                (
                    "limit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="지정가",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "체결 대기"),
                            ("COMPLETED", "체결 완료"),
                            ("FAILED", "주문 실패"),
                            ("CANCELED", "주문 취소"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="주문 상태",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="주문 시간"),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stocks.stock",
                        verbose_name="주문 종목",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="주문자",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("BUY", "매수"), ("SELL", "매도")],
                        max_length=4,
                        verbose_name="거래 유형",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="체결 수량")),
                (
                    "executed_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="체결 가격"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="체결 시간"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="trading.order",
                        verbose_name="원본 주문",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stocks.stock",
                        verbose_name="거래 종목",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="거래자",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_quantity",
                    models.PositiveIntegerField(default=0, verbose_name="총 보유 수량"),
                ),
                (
                    "average_purchase_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="평균 매수 단가",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stocks.stock",
                        verbose_name="보유 종목",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="소유자",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "stock")},
            },
        ),
    ]
