# Generated by Django 5.2.7 on 2025-10-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cash_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=10000000.0,
                max_digits=15,
                verbose_name="예수금",
            ),
        ),
    ]
