# Generated by Django 5.2.7 on 2025-10-22 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_cash_balance"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_date", models.DateField(verbose_name="스냅샷 날짜")),
                (
                    "total_asset",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="총 자산"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "월말 자산 기록",
                "verbose_name_plural": "월말 자산 기록 목록",
                "ordering": ["snapshot_date"],
                "unique_together": {("user", "snapshot_date")},
            },
        ),
    ]
